---
- name: Remove web server
  hosts: webservers
  become: true
  remote_user: user

  tasks:
    - name: Remove httpd
      yum:
        name: httpd
        state: absent

    - name: Disable firewall port
      firewalld:
        service: http
        permanent: true
        state: disabled
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service:
        name: firewalld
        state: restarted
